### ISSUE TITLE
Astro + vite integration

### ISSUE THREAD

**Issue by fcabouat** [scala-js/vite-plugin-scalajs#12]
Hello,

Does this plugin work with Astro ? Is there a working example out there?

Cheers,

François

**Comment by sjrd** [comment]
I don't know. I don't know Astro. I suggest you give it a try.

**Comment by fcabouat** [comment]
The idea was to use Astro as a static site generator that embeds Vite + some scalajs interactivity.

It seems that just adding the scalajs plugin naively in the vite plugins section of Astro config doesn't do the trick, and I don't know the lifecycles of all of those tools enough to get what hook might be missing, or how to tell the plugin to process .astro template files.

![image](https://github.com/scala-js/vite-plugin-scalajs/assets/17034829/aa4773ed-6efa-4449-9cb7-b9cd846959ae)

**Comment by fcabouat** [comment]
Sorry, issues were with the Astro config, not the Vite ScalaJs config.

I restarted from scratch, not with the Astro Getting Started but taking inspiration from : https://astro.build/themes/details/astro-vanilla-ts/ (closer to my intended usecase), and I can confirm I managed to get a Hello World from Scala / it works perfectly !

Sorry for the noise,

François
