### ISSUE TITLE
Hot Reload is not working

### ISSUE THREAD

**Issue by dejvid** [scala-js/vite-plugin-scalajs#15]
I have tried you example, but modifying .scala files doesnt trigger recompilation in sbt. I have run project with npm run dev. Looks like that SBT is not running in WATCH mode. Am I missing something?

**Comment by sjrd** [comment]
You need *both* a process running `npm run dev` and one running `sbt ~fastLinkJS` (or `sbt`, and then, inside its shell, `~fastLinkJS`).
